page_order: ["Crew", "Personlig info", "Tilstedeværelse"]
Crew:
  1:
    type: crew
    question: "Hvilket crew ønsker du som første valg?"
  2:
    type: crew
    question: "Hvilket crew ønsker du som andre valg?"
  3:
    type: string
    default: ""
    question: "Hva slags relevant erfaring har du?"

Personlig info:
  1:
    type: string
    default: ""
    question: "Har du noen allergier?"
  2:
    type: string
    default: ""
    question: "Har du noen sykdommer eller lignende, som vi bør vite om?"
  3:
    type: string
    default: ""
    question: "Vennligst oppgi en kontakt-person i tilfelle noe oppstår. (navn og nummer)"

Tilstedeværelse:
  1:
    type: radio
    default: "yes"
    question: "Er du tilgjengelig ved opprigg?"
  2:
    type: radio
    default: "yes"
    question: "Er du tilgjengelig ved nedrigg?"
  3:
    type: radio
    default: "yes"
    question: "Er du tilgjengelig ved selve LANet?"
  4:
    type: string
    default: ""
    question: "Fyll ut ekstra relevant informasjon i henhold til tilstedeværelse."
